//! CsmModelConfig — wires MimiConfig + BackboneConfig + DepformerConfig into
//! a single, coherent configuration for the full CSM model assembly.

use opensesame_backbone::{BackboneConfig, AUDIO_NUM_CODEBOOKS, AUDIO_VOCAB_SIZE, TEXT_VOCAB_SIZE};
use opensesame_depformer::DepformerConfig;
use opensesame_mimi::MimiConfig;

// ── CsmModelConfig ────────────────────────────────────────────────────────────

/// Configuration for the full CSM model (Mimi + Backbone + Depformer).
///
/// Wires together three sub-configs and adds top-level generation hyper-parameters.
///
/// # Example (full 1B model)
/// ```
/// # use opensesame_csm::CsmModelConfig;
/// let cfg = CsmModelConfig::opensesame_1b();
/// assert_eq!(cfg.n_codebooks, 32);
/// assert_eq!(cfg.backbone_dim, 2048);
/// assert_eq!(cfg.decoder_dim, 1024);
/// ```
#[derive(Debug, Clone)]
pub struct CsmModelConfig {
    /// Mimi audio codec configuration (encoder/decoder + RVQ quantizer).
    pub mimi: MimiConfig,
    /// Backbone transformer configuration (Llama-style, processes multimodal context).
    pub backbone: BackboneConfig,
    /// Depformer configuration (generates CB1..CBn−1 per frame).
    pub depformer: DepformerConfig,
    /// Total number of active RVQ codebooks (8 for Moshi, 32 for CSM-1B).
    pub n_codebooks: usize,
    /// Text token vocabulary size (128_256 for Llama 3.2).
    pub text_vocab: usize,
    /// Audio token vocabulary size per codebook (2048 for Mimi).
    pub audio_vocab: usize,
    /// Backbone hidden dimension (2048 for CSM-1B).
    pub backbone_dim: usize,
    /// Depformer hidden dimension (1024 for CSM-1B).
    pub decoder_dim: usize,
    /// Sampling temperature.  0.0 = greedy argmax, 1.0 = standard.
    pub temperature: f32,
    /// Top-k sampling cutoff (0 = no cutoff).
    pub topk: usize,
    /// Number of PCM samples per Mimi frame (1920 at 24 kHz / 12.5 fps).
    pub frame_samples: usize,
}

impl CsmModelConfig {
    /// Full OpenSesame-1B configuration.
    ///
    /// Matches the production CSM-1B model from SesameAILabs with 32 codebooks,
    /// Llama-3.2-1B backbone, and Llama-3.2-100M depformer.
    pub fn opensesame_1b() -> Self {
        let mimi = MimiConfig::csm_32();
        let backbone = BackboneConfig::csm_1b();
        let depformer = DepformerConfig::opensesame_1b();
        let frame_samples = mimi.hop_length();
        Self {
            n_codebooks:  AUDIO_NUM_CODEBOOKS, // 32
            text_vocab:   TEXT_VOCAB_SIZE,     // 128_256
            audio_vocab:  AUDIO_VOCAB_SIZE,    // 2048
            backbone_dim: 2048,
            decoder_dim:  1024,
            temperature:  1.0,
            topk:         50,
            frame_samples,
            mimi,
            backbone,
            depformer,
        }
    }

    /// Tiny configuration for fast unit tests (2 backbone layers, d=64).
    ///
    /// Uses 4 codebooks, 16-entry audio vocabulary, and 200-token text vocabulary
    /// so that models can be created and tested without significant memory usage.
    pub fn tiny() -> Self {
        let mut mimi = MimiConfig::v0_1(); // 8-codebook base
        mimi.num_codebooks = 4;
        mimi.max_codebooks = 8; // keep max=8 so we can call set_num_codebooks(4)
        let frame_samples = mimi.hop_length();

        let backbone = BackboneConfig::tiny();  // d=64, 4 codebooks, vocab=16

        // Tiny depformer: 1 layer, d=64 (matches backbone_dim), 4 codebooks total
        let depformer = DepformerConfig {
            n_layers:        1,
            d_model:         64,
            n_heads:         2,
            n_kv_heads:      2,
            head_dim:        32,     // 64 / 2
            ffn_dim:         64,
            n_codebooks:     4,      // CB0..CB3
            n_dep_codebooks: 3,      // CB1..CB3 generated by depformer
            vocab_size:      16,     // audio_vocab_size for tiny
            d_backbone:      64,     // backbone_dim for tiny
            rope_base:       10_000.0,
            norm_eps:        1e-5,
        };

        Self {
            n_codebooks:  4,
            text_vocab:   200,  // BackboneConfig::tiny().text_vocab_size
            audio_vocab:  16,   // BackboneConfig::tiny().audio_vocab_size
            backbone_dim: 64,   // BackboneConfig::tiny().d_model
            decoder_dim:  64,   // depformer d_model (same as backbone for tiny)
            temperature:  1.0,
            topk:         4,
            frame_samples,
            mimi,
            backbone,
            depformer,
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_config_opensesame_1b() {
        let cfg = CsmModelConfig::opensesame_1b();
        assert_eq!(cfg.n_codebooks, 32, "32 codebooks for CSM-1B");
        assert_eq!(cfg.text_vocab, 128_256, "text vocab = 128_256");
        assert_eq!(cfg.audio_vocab, 2_048, "audio vocab = 2048");
        assert_eq!(cfg.backbone_dim, 2_048, "backbone dim = 2048");
        assert_eq!(cfg.decoder_dim, 1_024, "decoder dim = 1024");
        assert!((cfg.temperature - 1.0).abs() < 1e-6, "default temperature = 1.0");
        assert_eq!(cfg.topk, 50, "default topk = 50");
        assert_eq!(cfg.frame_samples, 1920, "frame_samples = 1920 at 24kHz / 12.5fps");
    }

    #[test]
    fn test_config_tiny() {
        let cfg = CsmModelConfig::tiny();
        assert_eq!(cfg.n_codebooks, 4, "tiny has 4 codebooks");
        assert_eq!(cfg.backbone_dim, 64, "tiny backbone_dim = 64");
        assert_eq!(cfg.decoder_dim, 64, "tiny decoder_dim = 64");
        assert_eq!(cfg.audio_vocab, 16, "tiny audio_vocab = 16");
        assert_eq!(cfg.text_vocab, 200, "tiny text_vocab = 200");
        // n_dep_codebooks = n_codebooks - 1
        assert_eq!(cfg.depformer.n_dep_codebooks, 3, "tiny depformer: 3 dep codebooks");
        assert_eq!(cfg.depformer.d_model, 64, "tiny depformer d=64");
    }

    #[test]
    fn test_config_1b_backbone_matches() {
        let cfg = CsmModelConfig::opensesame_1b();
        // Backbone config should match
        assert_eq!(cfg.backbone.d_model, cfg.backbone_dim);
        assert_eq!(cfg.backbone.n_audio_codebooks, cfg.n_codebooks);
        assert_eq!(cfg.backbone.audio_vocab_size, cfg.audio_vocab);
        assert_eq!(cfg.backbone.text_vocab_size, cfg.text_vocab);
    }

    #[test]
    fn test_config_tiny_backbone_matches() {
        let cfg = CsmModelConfig::tiny();
        assert_eq!(cfg.backbone.d_model, cfg.backbone_dim);
        assert_eq!(cfg.backbone.n_audio_codebooks, cfg.n_codebooks);
    }
}
