//! Depformer configuration — Llama-3.2-100M-scale transformer.
//!
//! The Depformer is the lightweight autoregressive decoder that generates
//! codebook tokens CB1..CB7 for each audio frame, conditioned on the
//! backbone hidden state projected to the 1024-dimensional depformer space.

/// Depformer configuration: 4-layer Llama-style transformer.
///
/// Matches the `ModelArgs(decoder_flavor=Llama100M)` configuration in the
/// Sesame CSM source (`SesameAILabs/csm models.py`, Apache 2.0).
#[derive(Debug, Clone)]
pub struct DepformerConfig {
    /// Number of transformer layers. CSM-1B default: 4.
    pub n_layers: usize,
    /// Hidden (model) dimension. CSM-1B default: 1024.
    pub d_model: usize,
    /// Number of query attention heads. CSM-1B default: 8.
    pub n_heads: usize,
    /// Number of key/value heads (GQA). CSM-1B default: 2.
    pub n_kv_heads: usize,
    /// Per-head dimension = `d_model / n_heads`. CSM-1B: 128.
    pub head_dim: usize,
    /// FFN intermediate dimension (SwiGLU). CSM-1B default: 8192.
    pub ffn_dim: usize,
    /// Total codebooks including CB0. CSM-1B default: 8.
    pub n_codebooks: usize,
    /// Codebooks generated by depformer (CB1..CB7). CSM-1B default: 7.
    pub n_dep_codebooks: usize,
    /// Audio token vocabulary size per codebook. CSM-1B default: 2048.
    pub vocab_size: usize,
    /// Backbone hidden dimension (input projection source). CSM-1B default: 2048.
    pub d_backbone: usize,
    /// RoPE base frequency. CSM-1B default: 500_000.0 (Llama 3.2 extended).
    pub rope_base: f32,
    /// RMSNorm epsilon. CSM-1B default: 1e-5.
    pub norm_eps: f32,
}

impl DepformerConfig {
    /// OpenSesame CSM-1B depformer configuration.
    ///
    /// Returns the configuration for the Llama-3.2-100M-scale depth transformer
    /// used in the Sesame CSM-1B model.
    pub fn opensesame_1b() -> Self {
        Self {
            n_layers:         4,
            d_model:          1024,
            n_heads:          8,
            n_kv_heads:       2,
            head_dim:         128,    // 1024 / 8
            ffn_dim:          8192,
            n_codebooks:      8,      // CB0..CB7
            n_dep_codebooks:  7,      // CB1..CB7 generated by depformer
            vocab_size:       2048,
            d_backbone:       2048,
            rope_base:        500_000.0,
            norm_eps:         1e-5,
        }
    }

    /// Convert to `atlas_model::ModelConfig` for `OlmoModel` construction.
    ///
    /// `max_seq_len` is set to `n_codebooks` (= 8): the KV cache holds exactly
    /// one audio frame's depth sequence (backbone projection + 7 codebook steps).
    pub fn to_model_config(&self) -> atlas_model::ModelConfig {
        atlas_model::ModelConfig {
            vocab_size:    self.vocab_size,
            d_model:       self.d_model,
            n_layers:      self.n_layers,
            n_heads:       self.n_heads,
            n_kv_heads:    self.n_kv_heads,
            ffn_hidden:    self.ffn_dim,
            max_seq_len:   self.n_codebooks,   // 8 positions per frame
            rope_theta:    self.rope_base,
            rms_norm_eps:  self.norm_eps,
            layer_types:   Vec::new(),
            sliding_window: None,
            rope_scaling:  atlas_model::RopeScaling::None,
            eos_token_id:  None,
        }
    }
}
