//! Depformer struct — the depth transformer for per-frame codebook generation.
//!
//! The Depformer generates codebook tokens CB1..CB7 autoregressively for each
//! audio frame.  It runs as a small (4-layer, 1024-dim) Llama-style transformer
//! whose KV cache is **reset at the start of every frame** — it has no temporal
//! memory across frames, only depth-within-frame attention.
//!
//! # Generation loop (per frame)
//! ```text
//! depth 0: forward(proj_h)      → h0  [primes KV cache; output discarded]
//! depth 1: forward(embed(CB0))  → h1  → audio_head[0](h1) → CB1
//! depth 2: forward(embed(CB1))  → h2  → audio_head[1](h2) → CB2
//! ...
//! depth 7: forward(embed(CB6))  → h7  → audio_head[6](h7) → CB7
//! ```

use crate::config::DepformerConfig;
use crate::head::CsmAudioHead;
use crate::sampling::sample_topk;

/// The Depformer: generates audio codebook tokens CB1..CB7 per audio frame.
///
/// Wraps an `atlas_model::OlmoModel` (4 layers, 1024-dim) with per-depth
/// output heads stored in [`CsmAudioHead`].
pub struct Depformer {
    /// Shared 4-layer Llama-style transformer.
    pub transformer: atlas_model::OlmoModel,
    /// Per-depth output projection heads (CB1..CB7).
    pub head: CsmAudioHead,
    /// Model configuration.
    pub config: DepformerConfig,
}

impl Depformer {
    /// Create a Depformer with deterministic random weights.
    ///
    /// The transformer uses `OlmoModel::new` (seeded random via `atlas-model`'s
    /// internal `pseudo_randn`).  The audio heads use a seeded XORSHIFT-64 RNG.
    /// Two calls with the same `DepformerConfig` produce identical weights,
    /// enabling reproducible tests.
    ///
    /// This is the recommended constructor for unit tests and benchmarks.
    pub fn new(config: DepformerConfig) -> Self {
        let transformer = atlas_model::OlmoModel::new(config.to_model_config());
        let head = CsmAudioHead::random(
            config.n_dep_codebooks,
            config.d_model,
            config.vocab_size,
            0xDEAD_BEEF_1234_5678u64,
        );
        Self { transformer, head, config }
    }

    /// Create a Depformer with zero-initialized audio heads.
    ///
    /// The transformer still uses random initialization (from `OlmoModel::new`).
    /// Use this before loading weights from a safetensors checkpoint.
    pub fn new_zeroed(config: DepformerConfig) -> Self {
        let transformer = atlas_model::OlmoModel::new(config.to_model_config());
        let head = CsmAudioHead::zeros(
            config.n_dep_codebooks,
            config.d_model,
            config.vocab_size,
        );
        Self { transformer, head, config }
    }

    /// Reset the KV cache for a new audio frame.
    ///
    /// Sets the internal position counter to 0.  Old KV entries are never
    /// read after reset (the attention kernel reads `keys[0..pos]`) so
    /// zeroing is not required.
    ///
    /// Must be called once at the start of processing each 80 ms audio frame.
    pub fn reset_for_frame(&mut self) {
        self.transformer.reset();
    }

    /// Process one depth step: feed an input embedding and return the hidden state.
    ///
    /// Internally tries the GPU path (`forward_hidden_raw_gpu`) first, falling
    /// back to CPU (`forward_hidden_raw`) if CUDA is unavailable.
    ///
    /// `input`: `[d_model]` projected token embedding.
    /// Returns: `[d_model]` hidden state after all transformer layers + final norm.
    pub fn forward_step(&mut self, input: Vec<f32>) -> Vec<f32> {
        self.transformer
            .forward_hidden_raw_gpu(input.clone())
            .unwrap_or_else(|| self.transformer.forward_hidden_raw(input))
    }

    /// Run the complete depth decode loop for one audio frame.
    ///
    /// Generates `n_dep_codebooks` (= 7) tokens CB1..CB7 autoregressively.
    ///
    /// # Arguments
    /// - `proj_h`:        `[d_model=1024]` — backbone hidden state **already projected**
    ///   to depformer space (via the `Linear(2048→1024)` backbone projection).
    /// - `prev_embed_fn`: closure `(cb_idx: usize, prev_code: u32) → Vec<f32>[d_model]`.
    ///   Called as `prev_embed_fn(depth-1, previous_code)` at each depth step to look
    ///   up and project the previous codebook token embedding.
    /// - `temperature`:   sampling temperature (0.0 = greedy argmax).
    /// - `topk`:          keep only top-k logits (0 = no filtering).
    /// - `cb0`:           CB0 token already generated by the backbone CB0 head.
    ///
    /// # Returns
    /// `Vec<u32>` of length `n_dep_codebooks` containing CB1..CB7 token IDs.
    pub fn generate_depth_sequence<F>(
        &mut self,
        proj_h: Vec<f32>,
        mut prev_embed_fn: F,
        temperature: f32,
        topk: usize,
        cb0: u32,
    ) -> Vec<u32>
    where
        F: FnMut(usize, u32) -> Vec<f32>,
    {
        self.reset_for_frame();

        // Depth 0: backbone projection primes the KV cache.
        // The output hidden state is discarded — its only purpose is to write
        // position 0 into K and V caches so that later depth steps can attend to it.
        let _h0 = self.forward_step(proj_h);

        // Depths 1..n_dep_codebooks: autoregressively generate CB1..CB7.
        let mut codes = Vec::with_capacity(self.config.n_dep_codebooks);
        let mut prev_code = cb0;

        for depth in 1..=self.config.n_dep_codebooks {
            // Get the projected embedding of the previous codebook token.
            let dep_input = prev_embed_fn(depth - 1, prev_code);

            // Forward one depth step through the transformer.
            let h = self.forward_step(dep_input);

            // Apply the per-depth output head to get logits.
            let mut logits = vec![0.0f32; self.config.vocab_size];
            self.head.forward(depth, &h, &mut logits);

            // Sample next token.
            let code = sample_topk(&logits, topk, temperature);
            codes.push(code);
            prev_code = code;
        }

        codes
    }
}
