// Tests 1–4: DepformerConfig

use opensesame_depformer::DepformerConfig;

/// TEST 1: All CSM-1B constants are correct (corrected from HF checkpoint).
#[test]
fn depformer_config_constants() {
    let cfg = DepformerConfig::opensesame_1b();
    assert_eq!(cfg.n_layers,         4);
    assert_eq!(cfg.d_model,          1024);
    assert_eq!(cfg.n_heads,          8);
    assert_eq!(cfg.n_kv_heads,       2);
    assert_eq!(cfg.head_dim,         128);    // 1024 / 8
    assert_eq!(cfg.ffn_dim,          8192);
    assert_eq!(cfg.n_codebooks,      32);     // CB0..CB31
    assert_eq!(cfg.n_dep_codebooks,  31);     // CB1..CB31 generated by depformer
    assert_eq!(cfg.vocab_size,       2051);   // EOS=0, normal=1..2048, pad=2050
    assert_eq!(cfg.d_backbone,       2048);
    assert!((cfg.rope_base - 500_000.0).abs() < 1.0, "rope_base should be 500_000");
    assert!((cfg.rope_scale - 32.0).abs() < 0.1, "rope_scale should be 32 (Llama 3.2 YaRN)");
}

/// TEST 2: to_model_config round-trips all fields and enables YaRN RoPE.
#[test]
fn depformer_to_model_config() {
    use atlas_model::RopeScaling;
    let cfg = DepformerConfig::opensesame_1b();
    let mc = cfg.to_model_config();
    assert_eq!(mc.d_model,     1024);
    assert_eq!(mc.n_layers,    4);
    assert_eq!(mc.n_heads,     8);
    assert_eq!(mc.n_kv_heads,  2);
    assert_eq!(mc.ffn_hidden,  8192);
    assert_eq!(mc.max_seq_len, 32);   // n_codebooks = 32 (1 backbone + 31 depth steps)
    assert!((mc.rope_theta - 500_000.0).abs() < 1.0);
    // Confirm YaRN RoPE is enabled (Llama 3.2 scale_factor=32)
    match &mc.rope_scaling {
        RopeScaling::Yarn { factor, orig_max_pos, .. } => {
            assert!((*factor - 32.0).abs() < 0.1, "YaRN factor should be 32");
            assert_eq!(*orig_max_pos, 8192, "orig_max_pos should be 8192");
        }
        RopeScaling::None => panic!("depth decoder must use YaRN RoPE, got None"),
    }
}

/// TEST 3: GQA group size is 4.
#[test]
fn depformer_gqa_groups() {
    let cfg = DepformerConfig::opensesame_1b();
    let groups = cfg.n_heads / cfg.n_kv_heads;
    assert_eq!(groups, 4);
}

/// TEST 4: head_dim = d_model / n_heads.
#[test]
fn depformer_head_dim_consistent() {
    let cfg = DepformerConfig::opensesame_1b();
    assert_eq!(cfg.head_dim, cfg.d_model / cfg.n_heads);
    assert_eq!(cfg.head_dim, 128);
}
